export const BOOKING_CAR_REQUEST = 'BOOKING_CAR_REQUEST';
export const BOOKING_CAR_SUCCESS = 'BOOKING_CAR_SUCCESS';
export const BOOKING_CAR_FAIL = 'BOOKING_CAR_FAIL';
export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
